# Move focus
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, J, movefocus, d
bind = SUPER, K, movefocus, u

# Resize windows
bind = SUPER SHIFT, H, resizeactive, -60 0
bind = SUPER SHIFT, L, resizeactive, 60 0
bind = SUPER SHIFT, J, resizeactive, 0 60
bind = SUPER SHIFT, K, resizeactive, 0 -60

# Make focused window the main one
bind = SUPER, RETURN, layoutmsg, swapwithmaster

# Toggle floating (VERY IMPORTANT)
bind = SUPER, SPACE, togglefloating

# Close window
bind = SUPER, Q, killactive
# Move window in layout
bind = SUPER SHIFT, H, movewindow, l
bind = SUPER SHIFT, L, movewindow, r
bind = SUPER SHIFT, J, movewindow, d
bind = SUPER SHIFT, K, movewindow, u

#toggle master layout orientation 


# Force master orientation (bulletproof)
bind = SUPER, TAB, exec, hyprctl keyword master:orientation top
bind = SUPER SHIFT, TAB, exec, hyprctl keyword master:orientation left
#wofi and app binds
bind = SUPER, D, exec, wofi  --show drun
bind = SUPER SHIFT, Q, exec, ~/.config/wofi/powermenu.sh
