# Focused / unfocused opacity (all apps)
windowrulev2 = opacity 0.94 0.75, floating:0
windowrulev2 = opacity 0.92 0.70, floating:1

# Apply blur everywhere
windowrulev2 = blur, class:.*

windowrulev2 = float, class:^(thunar|pavucontrol|blueman-manager)$
windowrulev2 = center, floating:1

