#!/usr/bin/env bash
# Generate native theme adapters from palette.toml. Do not edit theme/generated/*.
set -euo pipefail

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
palette="$script_dir/palette.toml"
output_dir="$script_dir/generated"
install_live=false

case "${1:-}" in
    "") ;;
    --install) install_live=true ;;
    -h|--help)
        printf 'Usage: %s [--install]\n\n--install copies adapters into active ~/.config program directories.\n' "$0"
        exit 0
        ;;
    *) printf 'Unknown option: %s\n' "$1" >&2; exit 2 ;;
esac

declare -a required=(
    base surface surface_raised text text_muted selection_bg selection_text accent accent_bright accent_soft
    border_active border_inactive danger warning success
)
declare -A colors=()

while IFS='=' read -r raw_key raw_value; do
    key=$(printf '%s' "$raw_key" | tr -d '[:space:]')
    value=$(printf '%s' "$raw_value" | tr -d '[:space:]\"')
    [[ -z "$key" || "$key" == \#* ]] && continue
    found=false
    for expected in "${required[@]}"; do [[ "$key" == "$expected" ]] && found=true && break; done
    "$found" || { printf 'Unexpected palette key: %s\n' "$key" >&2; exit 1; }
    [[ ! -v "colors[$key]" ]] || { printf 'Duplicate palette key: %s\n' "$key" >&2; exit 1; }
    [[ "$value" =~ ^#[0-9A-Fa-f]{6}$ ]] || { printf 'Invalid color for %s: %s\n' "$key" "$value" >&2; exit 1; }
    colors[$key]="${value^^}"
done < "$palette"

for key in "${required[@]}"; do
    [[ -v "colors[$key]" ]] || { printf 'Missing palette key: %s\n' "$key" >&2; exit 1; }
done

hex() { printf '%s' "${colors[$1]#\#}"; }
css_definitions() {
    for key in "${required[@]}"; do printf '@define-color theme-%s %s;\n' "${key//_/-}" "${colors[$key]}"; done
}

mkdir -p "$output_dir"

{
    printf '# Generated by theme/generate-theme.sh from theme/palette.toml; do not edit.\n'
    printf '# Semantic palette is expressed in native Hyprland colors.\n\n'
    printf 'general {\n'
    printf '    col.active_border = rgba(%sff)\n' "$(hex border_active)"
    printf '    col.inactive_border = rgba(%sff)\n' "$(hex border_inactive)"
    printf '}\n\n'
    printf 'decoration {\n    shadow {\n        color = rgba(%see)\n    }\n}\n' "$(hex base)"
} > "$output_dir/hyprland.conf"

{
    printf '/* Generated by theme/generate-theme.sh from theme/palette.toml; do not edit. */\n'
    css_definitions
    cat <<EOF

/* Compatibility aliases for the existing Waybar component stylesheet. */
@define-color primary ${colors[accent_bright]};
@define-color primary-container ${colors[accent_soft]};
@define-color on-primary ${colors[base]};
@define-color on-primary-container ${colors[text]};
@define-color secondary ${colors[text_muted]};
@define-color secondary-container ${colors[surface_raised]};
@define-color on-secondary ${colors[base]};
@define-color on-secondary-container ${colors[text]};
@define-color tertiary ${colors[accent]};
@define-color tertiary-container ${colors[accent_soft]};
@define-color on-tertiary ${colors[text]};
@define-color on-tertiary-container ${colors[text]};
@define-color error ${colors[danger]};
@define-color error-container ${colors[danger]};
@define-color on-error ${colors[base]};
@define-color on-error-container ${colors[text]};
@define-color outline ${colors[border_active]};
@define-color background ${colors[base]};
@define-color on-background ${colors[text]};
@define-color surface ${colors[surface]};
@define-color on-surface ${colors[text]};
@define-color surface-variant ${colors[surface_raised]};
@define-color on-surface-variant ${colors[text_muted]};
@define-color selection-background ${colors[selection_bg]};
@define-color selection-foreground ${colors[selection_text]};
@define-color inverse-surface ${colors[text]};
@define-color inverse-on-surface ${colors[base]};
@define-color inverse-primary ${colors[accent]};
@define-color shadow ${colors[base]};
@define-color surface-tint ${colors[accent]};
@define-color outline-variant ${colors[border_inactive]};
@define-color scrim ${colors[base]};
@define-color green ${colors[success]};
@define-color red ${colors[danger]};
@define-color pastel-blue ${colors[accent_bright]};
@define-color pastel-pink ${colors[danger]};
@define-color pastel-green ${colors[success]};
@define-color pastel-yellow ${colors[warning]};
@define-color pastel-purple ${colors[accent]};
@define-color pastel-orange ${colors[warning]};
@define-color pastel-lavender ${colors[text]};
@define-color pastel-mint ${colors[success]};
@define-color pastel-peach ${colors[warning]};
@define-color pastel-firefox-orange ${colors[warning]};
@define-color pastel-jetbrains-blue ${colors[accent_bright]};
@define-color pastel-chrome-yellow ${colors[warning]};
@define-color pastel-telegram-blue ${colors[accent_bright]};
@define-color pastel-chrome-blue ${colors[accent_bright]};
@define-color pastel-gitkraken-purple ${colors[accent]};
EOF
} > "$output_dir/waybar.css"

{
    printf '/* Generated by theme/generate-theme.sh from theme/palette.toml; do not edit. */\n'
    css_definitions
} > "$output_dir/wofi.css"

cat > "$output_dir/rofi.rasi" <<EOF
/* Generated by theme/generate-theme.sh from theme/palette.toml; do not edit. */
* {
    theme-base: ${colors[base]};
    theme-surface: ${colors[surface]};
    theme-surface-raised: ${colors[surface_raised]};
    theme-text: ${colors[text]};
    theme-text-muted: ${colors[text_muted]};
    theme-selection-bg: ${colors[selection_bg]};
    theme-selection-text: ${colors[selection_text]};
    theme-accent: ${colors[accent]};
    theme-accent-bright: ${colors[accent_bright]};
    theme-accent-soft: ${colors[accent_soft]};
    theme-border-active: ${colors[border_active]};
    theme-border-inactive: ${colors[border_inactive]};
    theme-danger: ${colors[danger]};
    theme-warning: ${colors[warning]};
    theme-success: ${colors[success]};
}
EOF

cat > "$output_dir/kitty.conf" <<EOF
# Generated by theme/generate-theme.sh from theme/palette.toml; do not edit.
background ${colors[base]}
foreground ${colors[text]}
cursor ${colors[accent_bright]}
selection_background ${colors[selection_bg]}
selection_foreground ${colors[selection_text]}
active_border_color ${colors[border_active]}
inactive_border_color ${colors[border_inactive]}
color0 ${colors[base]}
color1 ${colors[danger]}
color2 ${colors[success]}
color3 ${colors[warning]}
color4 ${colors[accent]}
color5 ${colors[accent_bright]}
color6 ${colors[accent_soft]}
color7 ${colors[text_muted]}
color8 ${colors[border_inactive]}
color9 ${colors[danger]}
color10 ${colors[success]}
color11 ${colors[warning]}
color12 ${colors[accent_bright]}
color13 ${colors[accent_bright]}
color14 ${colors[accent_soft]}
color15 ${colors[text]}
EOF

{
    printf '/* Generated by theme/generate-theme.sh from theme/palette.toml; do not edit. */\n'
    css_definitions
    cat <<EOF

control-center, .notification, .notification-content, .close-button {
    background: @theme-surface;
    color: @theme-text;
    border-color: @theme-border-inactive;
}
.notification.critical { border-color: @theme-danger; }
.notification-action { background: @theme-accent-soft; color: @theme-text; }
.notification-action:hover { background: @theme-accent; }
.notification-action:focus, textview selection, entry selection {
    background: @theme-selection-bg;
    color: @theme-selection-text;
}
EOF
} > "$output_dir/swaync.css"

if "$install_live"; then
    config_root="${XDG_CONFIG_HOME:-$HOME/.config}"
    install -Dm644 "$output_dir/hyprland.conf" "$config_root/hypr/generated/theme.conf"
    install -Dm644 "$output_dir/waybar.css" "$config_root/waybar/styling/colors-waybar.css"
    install -Dm644 "$output_dir/wofi.css" "$config_root/wofi/theme-generated.css"
    install -Dm644 "$output_dir/rofi.rasi" "$config_root/rofi/theme-generated.rasi"
    install -Dm644 "$output_dir/kitty.conf" "$config_root/kitty/theme-generated.conf"
    install -Dm644 "$output_dir/swaync.css" "$config_root/swaync/style.css"
fi

printf 'Generated adapters in %s\n' "$output_dir"
if "$install_live"; then printf 'Installed adapters under %s\n' "${XDG_CONFIG_HOME:-$HOME/.config}"; fi
